### ISSUE TITLE
No 10 minute timer

### ISSUE THREAD

**Issue by miamurrell** [luketurner/PersonalPVT#2]
Hi, 

I have been using this PVT version for my dissertation (thank you btw!) But I have recently realised that the task no longer stops after 600 seconds, meaning my participants aren't able to end the task and see their scores. Is this able to be fixed at all? 

Thanks!
Mia

**Comment by luketurner** [comment]
Hi, thanks for the bug submission! It's been a while (a _long_ while!) since I've looked at this code but I'm thinking there is an issue with the way the "Trial Instructions" page uses the same timer as the actual trial page.

Replication:

1. Open trial settings page
2. Set Trial Length to 10 seconds (just so we don't have to wait 10 minutes to see what happens)
3. Check the "Show Instructions" option
4. Start a trial

The trial will continue longer than 10 seconds.

If in Step 3 you uncheck Show Instructions instead, the trial stops after 10 seconds.

I think I see why this is happening, I'll go ahead and try a simple fix.

**Comment by luketurner** [comment]
Just merged the fix -- let me know if you run into the problem again!
